### ISSUE TITLE
LAS配置信息有误，训练失败

### ISSUE THREAD

**Issue by hlp-ai** [hlp-ai/hlp#212]
加载数据并预处理......
Traceback (most recent call last):
  File "D:/hlp/github/hlp/hlp/stt/las/train.py", line 99, in <module>
    num_examples)
  File "D:\hlp\github\hlp\hlp\stt\las\data_processing\load_dataset.py", line 89, in load_data
    audio_data_path_list, text_list = load_dataset_number(wav_path, label_path, num_examples)
  File "D:\hlp\github\hlp\hlp\stt\las\data_processing\load_dataset.py", line 60, in load_dataset_number
    files = os.listdir(wav_path)  # 得到数据文件夹下的所有文件名称list    
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '.\\data\\wav_train'

Process finished with exit code 1

**Comment by hlp-ai** [comment]
好像数据处理也有问题，语音文本文件中的文件名和文本间的分隔符发生了改变？（\t变成了空格？）

**Comment by hlp-ai** [comment]
#218
