### ISSUE TITLE
NMT-tokenize模块和系统lib下的模块同名导致bleu和preprocess执行出错

### ISSUE THREAD

**Issue by hlp-ai** [hlp-ai/hlp#295]
bleu模块和prerpocess执行过程，有系统模块导入tokenize，这和项目的tokenize同名，导致导入项目的tokenzie模块，因而运行bleu和preprocess模块出错。

**Comment by hlp-ai** [comment]
D:\anaconda3\envs\py37tf2\python.exe D:/hlp/github/hlp/hlp/mt/commoneu.py
Traceback (most recent call last):
  File "D:/hlp/github/hlp/hlp/mt/commoneu.py", line 6, in <module>
    import numpy as np
  File "D:\anaconda3\envs\py37tf2\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "D:\anaconda3\envs\py37tf2\lib\site-packages\numpy\core\__init__.py", line 103, in <module>
    from . import _internal
  File "D:\anaconda3\envs\py37tf2\lib\site-packages\numpy\core\_internal.py", line 11, in <module>
    import platform
  File "D:\anaconda3\envs\py37tf2\lib\platform.py", line 116, in <module>
    import sys, os, re, subprocess
  File "D:\anaconda3\envs\py37tf2\lib\subprocess.py", line 126, in <module>
    import threading
  File "D:\anaconda3\envs\py37tf2\lib\threading.py", line 8, in <module>
    from traceback import format_exc as _format_exc
  File "D:\anaconda3\envs\py37tf2\lib\traceback.py", line 5, in <module>
    import linecache
  File "D:\anaconda3\envs\py37tf2\lib\linecache.py", line 11, in <module>
    import tokenize
  File "D:\hlp\github\hlp\hlp\mt\common\tokenize.py", line 15, in <module>
    import tensorflow_datasets as tfds
  File "D:\anaconda3\envs\py37tf2\lib\site-packages\tensorflow_datasets\__init__.py", line 47, in <module>
    from tensorflow_datasets.core import tf_compat
  File "D:\anaconda3\envs\py37tf2\lib\site-packages\tensorflow_datasets\core\__init__.py", line 21, in <module>
    from tensorflow_datasets.core import tf_compat
  File "D:\anaconda3\envs\py37tf2\lib\site-packages\tensorflow_datasets\core\tf_compat.py", line 27, in <module>
    from absl import logging
  File "D:\anaconda3\envs\py37tf2\lib\site-packages\absl\logging\__init__.py", line 82, in <module>
    import logging
  File "D:\anaconda3\envs\py37tf2\lib\logging\__init__.py", line 210, in <module>
    _lock = threading.RLock()
AttributeError: module 'threading' has no attribute 'RLock'

Process finished with exit code 1

**Comment by hlp-ai** [comment]
D:\anaconda3\envs\py37tf2\python.exe D:/hlp/github/hlp/hlp/mt/common/preprocess.py
Traceback (most recent call last):
  File "D:/hlp/github/hlp/hlp/mt/common/preprocess.py", line 10, in <module>
    from sklearn.model_selection import train_test_split
  File "D:\anaconda3\envs\py37tf2\lib\site-packages\sklearn\__init__.py", line 16, in <module>
    import logging
  File "D:\anaconda3\envs\py37tf2\lib\logging\__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections.abc
  File "D:\anaconda3\envs\py37tf2\lib\traceback.py", line 5, in <module>
    import linecache
  File "D:\anaconda3\envs\py37tf2\lib\linecache.py", line 11, in <module>
    import tokenize
  File "D:\hlp\github\hlp\hlp\mt\common\tokenize.py", line 15, in <module>
    import tensorflow_datasets as tfds
  File "D:\anaconda3\envs\py37tf2\lib\site-packages\tensorflow_datasets\__init__.py", line 47, in <module>
    from tensorflow_datasets.core import tf_compat
  File "D:\anaconda3\envs\py37tf2\lib\site-packages\tensorflow_datasets\core\__init__.py", line 21, in <module>
    from tensorflow_datasets.core import tf_compat
  File "D:\anaconda3\envs\py37tf2\lib\site-packages\tensorflow_datasets\core\tf_compat.py", line 27, in <module>
    from absl import logging
  File "D:\anaconda3\envs\py37tf2\lib\site-packages\absl\logging\__init__.py", line 95, in <module>
    from absl.logging import converter
  File "D:\anaconda3\envs\py37tf2\lib\site-packages\absl\logging\converter.py", line 52, in <module>
    STANDARD_CRITICAL = logging.CRITICAL
AttributeError: module 'logging' has no attribute 'CRITICAL'

Process finished with exit code 1

**Comment by hlp-ai** [comment]
#309
