### ISSUE TITLE
LAS-librispeech数据集支持按单词切分

### ISSUE THREAD

**Issue by hlp-ai** [hlp-ai/hlp#324]

**Comment by hlp-ai** [comment]
用en_word，出错：
开始训练...
Traceback (most recent call last):
  File "D:/hlp/github/hlp/hlp/stt/las/train.py", line 173, in <module>
    train_batch_size)  # 训练一个批次，返回批损失
  File "D:/hlp/github/hlp/hlp/stt/las/train.py", line 30, in train_step
    dec_input = tf.expand_dims([word_index['<start>']] * train_batch_size, 1)
KeyError: '<start>'

Process finished with exit code 1

**Comment by hlp-ai** [comment]
#326
