### ISSUE TITLE
TransformeTTS-合成语音max_mel_length问题

### ISSUE THREAD

**Issue by hlp-ai** [hlp-ai/hlp#330]
缺省1000没有依据，可以根据输入文本phoeneme长度给出一个更准确的上限（在没有引入stop判断的情况下）。使用缺省1000，合成出错。

Traceback (most recent call last):
  File "D:/hlp/github/hlp/hlp/tts/transformer/actuator.py", line 144, in <module>
    hop_length=options['hop_length'], win_length=options['win_length'])
  File "D:\hlp\github\hlp\hlp\tts\transformer\module.py", line 132, in generate
    num_mel, pre_emphasis, n_iter, hop_length, win_length)
  File "D:\hlp\github\hlp\hlp\tts\utils\spec.py", line 62, in melspectrogram2wav
    mag = np.dot(m, mel)
  File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (1025,80) and (1000,80) not aligned: 80 (dim 1) != 1000 (dim 0)

Process finished with exit code 1

**Comment by hlp-ai** [comment]
#333
