### ISSUE TITLE
TransformerTTS-train出错

### ISSUE THREAD

**Issue by hlp-ai** [hlp-ai/hlp#335]
正在加载训练数据...
从训练数据中划分验证数据...
训练验证数据加载完毕
Epoch 1/4
Traceback (most recent call last):
  File "D:/hlp/github/hlp/hlp/tts/transformer/actuator.py", line 136, in <module>
    max_train_data_size=options['max_train_data_size'], num_mel=options['num_mel'])
  File "D:\hlp\github\hlp\hlp\tts\transformer\module.py", line 62, in train
    print(' - {:.0f}s/step - loss: {:.4f}'.format((time.time() - start_time) / steps_per_epoch,
ZeroDivisionError: float division by zero

Process finished with exit code 1

**Comment by hlp-ai** [comment]
batch_size比例子数据集大。已修改。
